# 05. C# 1.0

## 5.2 프로젝트 구성

### 5.2.4 디버그 빌드와 릴리스 빌드

* 프로그램을 만들다 보면 크게 두 가지 오류를 접할 수 있다.
* 컴파일 오류, 런타임 오류
* Caller의 코드에 대상 메서드(Callee)의 코드가 포함되는 것을 inline됐다고 표현한다.
* 메서드의 코드를 인라인시키는 이유는 속도를 빠르게 하기 위해서다.
* 메서드로 호출하려면 매개변수를 전달하는 등의 작업을 해야하므로 상대적으로 속도 저하가 발생하기 때문이다.
* 최적화에는 인라인 외에도 여러가지 세세한 작업들이 포함된다. 이런 식으로 최적화를 허용하는 빌드를 릴리스 빌드라고 한다.
* 코드 최적화는 문제의 원인 파악을 어렵게 만든다.
* 오류 파악 관점에서 볼 때 릴리스 빌드에는 두 가지 주요 문제점이 있다.
* 하나는 문제가 발생한 소스코드의 라인 정보가 없다는 것이고 다른 하나는 최적화를 통해 메서드가 인라인됐다는 점이다.
* 문제가 발생한 소스코드 라인을 파악하기 위해서는 PDB(program database) 파일이 있어야 한다.
* 이 파일은 C# 컴파일러의 /debug 옵션으로 생성할 수 있다.
* /debug 옵션은 기본값으로 /dubug:full 과 동일하게 동작한다.
* 이 옵션을 지정해서 빌드된 EXE/DLL은 실행할 때 CLR에 의해 최적화 과정이 생략되고 개발자가 생성한 코드를 그대로 기계어로 번역한다.

#### 5.2.4.1 DEBUG, TRACE 전처리 상수

* DEBUG 상수는 디버그 빌드에서만 정의된다.
* TRACE 상수는 디버그, 릴리스 빌드 모두 정의된다.

```cs
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
#if DEBUG
            Console.WriteLine("디버그 빌드");
#endif
        }
    }
}
```

* 유사한 기능을 Conditional 특성으로 구현할 수 있다.
* 이 특성은 클래스와 메서드에 적용할 수 있다.
* Conditional 특성은 System.Diagnostics 네임스페이스에 정의되어 있다.

```cs
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            OutputText();
        }

        [Conditional("DEBUG")]
        static void OutputText() { Console.WriteLine("디버그빌드"); }
    }
}
```

#### 5.2.4.2 Debug 타입과 Trace 타입

```cs
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("사용자 화면 출력");
            Debug.WriteLine("디버그 화면 출력 - Debug");
            Trace.WriteLine("디버그 화면 출력 - Trace");
        }
    }
}
```

* 프로그램을 실행하면 화면에는 "사용자 화면 출력"만 출력된다.
* F5 단축키로 실행하면 실행되자마자 종료되고 하단의 출력(Output) 창에 Debug, Trace에서 결과를 확인할 수 있다.

### 5.2.5 플랫폼 선택

```cs
Console.WriteLine(Environment.Is64BitProcess);
// True, False 반환
```

### 5.2.6 버전 관리

* 보통의 경우 DLL 파일을 system32 폴더를 통해 공유한다. 하지만 DLL Hell 같은 문제를 발생한다.
* 닷넷은 이 문제를 전역 어셈블리 캐시(global assembly cache)와 강력한 이름의 어셈블리(strong-named assembly)라는 것을 도입해서 해결한다.

#### 5.2.6.1 어셈블리 버전과 이름

* 비주얼 스튜디오에서 생성한 프로젝트의 경우 자동으로 포함되는 AssemblyInfo.cs 파일에 버전 정보를 위한 AssemblyVersion 특성이 제공된다.

## 5.3 예외

### 5.3.1 예외 타입

* CLR에 의해 전달되는 예외는 그 자체도 Type의 인스턴스다.
* 새로운 예외 타입을 만드는 것도 가능하다.
* 개발자가 정의하는 예외는 System.Exception을 상속받은 System.ApplicationException을 상속받는다.
* 접미사로 Exception을 클래스명에 추가한다.
* CLR에서 미리 정의된 예외는 System.SystemException을 상속받는다.
* 이 규칙에 강제성이 부여된 것은 아니어서 마이크로소프트 내부적으로도 CLR의 일부 예외를 ApplicationException 타입에서 상속받아 정의했다.
* 최근에는 System.Exception에서 직접 상속받도록 권장한다.
* System.Exception 타입의 주요 멤버는 다음과 같다.
* Message: 인스턴스 프로퍼티 - 예외를 설명하는 메시지를 반환한다.
* Source: 인스턴스 프로퍼티 - 예외를 발생시킨 응용 프로그램의 이름을 반환한다.
* StackTrace: 인스턴스 프로퍼티 - 예외가 발생된 메서드의 호출 스택을 반환한다.
* ToString: 인스턴스 메서드 - Message, StackTrace 내용을 포함하는 문자열을 반환한다.

### 5.3.2 예외 처리기 exception handler

* 예외가 발생한 경우 CLR의 기본 처리 과정은 예외 메시지를 출력하고 프로그램을 종료하는 것이다.
* 예외 상황을 사용자에게 알리고 프로그램이 계속 실행되기를 원한다면 예외가 발생할 수 있는 코드를 try/catch로 묶어 둬야 한다.

```cs
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string txt = null;
                Console.WriteLine(txt.ToUpper());
            }
            catch (System.NullReferenceException) { }
            catch (System.DivideByZeroException) { }
            catch (System.Exception) { }
            finally { }
        }
    }
}
```

* catch 구문에는 예외 타입뿐 아니라 예외의 인스턴스를 변수로 받는 것도 가능하다.
* 이 변수를 이용하면 해당 예외 타입에서 제공되는 모든 멤버에 접근해서 정보를 가져올 수 있다.

```cs
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            int divide = 0;
            try
            {
                int quotient = 10 / divide;
            }
            catch (System.DivideByZeroException e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.Source);
                Console.WriteLine(e.StackTrace);
                Console.WriteLine("-------------------");
                Console.WriteLine(e.ToString());
            }
            catch (System.Exception) { }
        }
    }
}
```

### 5.3.4 예외 발생

* 예외를 임의로 발생시키는 것도 가능하다.

```cs
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string txt = null;
                Console.WriteLine(txt.ToUpper());
            }
            // catch (System.Exception ex) { throw ex; }
            catch (System.Exception) { throw; }
        }
    }
}
```

* throw ex 보다 throw 단독으로 사용하는 것이 좋다.
* throw를 단독으로 사용한 경우 예외를 발생시킨 호출 스택이 모두 출력된다.

### 5.3.5 사용자 정의 예외 타입

* 예외는 타입이다. 원한다면 별도의 클래스를 만들어 사용할 수 있다.

```cs
namespace ConsoleApp1
{
    class InvalidPasswordException : Exception
    {
        public InvalidPasswordException(string msg) : base(msg) { }
    }

    class Program
    {
        static void Main(string[] args)
        {
            string txt = Console.ReadLine();
            if (txt != "123")
            {
                InvalidPasswordException ex =
                    new InvalidPasswordException("틀린 함호");
                throw ex;
            }
            Console.WriteLine("올바른 암호");
        }
    }
}
```

* 현실적으로 사용 빈도는 그리 높지 않다.

### 5.3.6 올바른 예외 처리

* try/catch는 스레드 단위마다 단 한 번만 전역적으로 적용해야 한다.
* 스레드를 사용하지 않을 경우 Main 메서드에서 try/catch를 건다고 생각하면 된다.
* 예외 처리가 필요하다면 try/catch를 하더라도 catch에 정확한 예외 타입을 지정하는 것을 원칙으로 한다.
* 자원 수거가 목적인 try/finally 절은 자유롭게 사용할 수 있다.
* 예외가 발생한 경우의 처리는 매우 무겁다.
* Parse 메서드를 out 인자를 사용해 개선한 TryParse 메서드가 .NET 2.0 BCL에 포함되어 있다.
* 이 메서드는 문자열이 숫자로 바꿀 수 있는 경우에만 out 형식의 인자에 숫자값을 담고, 메서드 실행이 성공했는지 여부만 반환할 뿐 예외는 발생시키지 않는다.

```cs
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            int j;
            bool success = int.TryParse("5T", out j);
            Console.WriteLine(success);  // False
            Console.WriteLine(j);  // 0
        }
    }
}
```

* 예외 처리를 할 때 다음과 같은 규칙을 지키는 것이 좋다.
* 적어도 public 메서드에 한해서는 인자값이 올바른지 확인하거, 올바른 인자가 아니라면 예외를 발생시킨다.
* 예외를 범용적으로 catch 하는 것은 스레드마다 하나만 둔다. 그 외에는 catch 구문에는 반드시 예외 타입을 적용한다.
* try/finally의 조합은 언제든 사용할 수 있다.
* 성능상 문제가 발생할 수 있는 경우, 즉 호출 시 예외가 대량으로 발생하는 메서드가 있다면 예외 처리가 없는 메서드를 함께 제공한다.
